name: build
on: 
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository
        uses: actions/checkout@v3
      - name: Setup docker qemu
        uses: docker/setup-qemu-action@v1
      - name: Setup docker buildX
        uses: docker/setup-buildx-action@v1
      - name: Login Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name : Build and push docker
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/weather:latest